### PR TITLE
Makes it possible to display just a subset of the Jenkins jobs, by using 

### PR DESCRIPTION
**Pull request by cupcicm**
Makes it possible to display just a subset of the Jenkins jobs, by using index.php?view=view_name :
1. Adds the 'view' parameter to the JenkinsCI class. By default, it's null and points to all jobs.
2. getBuilds.php now uses $_GET['view'] to create the right JenkinsCI() instance.
3. In index.php, we forward the $_GET['view'] to getBuilds.php

### CODE REVIEW

**Comment by JakeWorrell** [comment]
Thanks for your contributions. 
Going to test this one at my end before I merge it in (I will need to do a manual merge anyway)

Out of interest, where/why/how are you using buildiator?

**Comment by cupcicm** [comment]
No problem, don't hesitate to adapt it in a way you like more. 

We are a small company in Paris who make heavy use of Jenkins. We are using buildiator because we think it's the best wall display "plugin" for Jenkins (pretty, easy to setup, easy to customize to your needs).

I still have a few changes that I might try to send you. Mostly :
1. display the name of the guy who claimed the build rather than the one who failed it.
2. Allow a custom css per view.

**Comment by JakeWorrell** [comment]
I've merged that now, thanks again :) 

I'm really pleased to hear you're using it and like it.

I'd love to receive those other changes you mentioned too, and if you can think of any changes/additions etc you would like to see then let me know.

I did consider a 'theme' option with custom css et al. but havent had chance to take a good look at that yet.

anyway, thanks again!

**Comment by cupcicm** [comment]
Sure, I'll try to send a few when I get some time to clean that code up. 

The "custom css" option I was refering to was much simpler than a whole theme framework, but it's useful in our setup : when you set your view to something non-default, e.g buildiator/?view=myview , it will try to load myview.css as well, so that each view can tweak things its way. The context is we basically have one "Wall Display" per team, and different teams want to show different things (views), and show them differently (custom css).

Hope it makes sense.

**Pull request merged**
